version: "3.4"

networks:
  traefik-net:
    external: true
  portainer_agent_network:
    driver: overlay

services:
  portainer:
    image: portainer/portainer
    networks:
      - traefik-net
      - portainer_agent_network
    volumes:
      - "/mnt/portainer:/data" # make sure to create mount /mnt/portainer
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:portainer.${HOST}.local
        - traefik.port=9000
        - traefik.docker.network=traefik-net
        - traefik.backend.loadbalancer.stickiness=true
      placement:
        constraints:
          - node.role == manager
      update_config:
          parallelism: 1
          delay: 10s
          order: start-first
    portainer_agent:
      image: portainer/agent:1.0.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - portainer_agent_network
      environment:
        # REQUIRED: Should be equal to the service name prefixed 
        # by "tasks." when deployed inside an overlay network
        AGENT_CLUSTER_ADDR: tasks.portainer_agent
      deploy:
        mode: global