version: "3.4"

services:
  keepalived:
    image: osixia/keepalived
    volumes:
      - "/etc/keepalived/environment:/container/environment/01-custom" # make sure to create volume /etc/keepalived/environment
    deploy:
      update_config:
          parallelism: 1
          delay: 15s
          order: start-first
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3