# NOTE: extension must be .yaml, not .yml or will not be loaded.

KEEPALIVED_COMMAND_LINE_ARGUMENTS: --log-detail --dump-conf

KEEPALIVED_INTERFACE: eth0
KEEPALIVED_PASSWORD: d0cker

# # For electing MASTER, highest priority wins.
# # to be MASTER, make 50 more than other machines
KEEPALIVED_PRIORITY: ${KEEPALIVED_PRIORITY}

KEEPALIVED_UNICAST_PEERS:
  - 192.168.99.100
  - 192.168.99.101
  - 192.168.99.102

KEEPALIVED_VIRTUAL_IPS:
  - 192.168.99.99

KEEPALIVED_NOTIFY: /container/service/keepalived/assets/notify.sh

KEEPALIVED_ROUTER_ID: 51